Msd gpu supports
JoonhoLee-Group/ipie pull request #299
Opened 2024-03-28 17:24 UTC by yfhuang93

New file: wicks_gpu.

Files with major changes: local_energy_wicks, green_function_multi_det, overlap.

First working version here. I'll add versions with more memory flexibility later.

2024-03-30 00:14 UTC, fdmalone commented on ipie/estimators/greens_function_multi_det.py
> +            phases = xp.ascontiguousarray(c_phasea_ovlpb[:, trial.excit_map_a[1]])
Can this be pushed own into the kernel call or no?

2024-03-30 00:14 UTC, fdmalone commented on ipie/estimators/greens_function_multi_det.py
> +        # print(type(trial.cre_ex_b[1]),type(trial.anh_ex_b[1]),type(trial.occ_map_b),type(phases),type(walker_batch_CIb))
Remove print.

2024-03-30 00:15 UTC, fdmalone commented on ipie/estimators/greens_function_multi_det.py
> +            # print(type(phases),type(walker_batch_Ghalfa),type(walker_batch_CIa))
Remove print.

2024-03-30 00:15 UTC, fdmalone commented on ipie/estimators/greens_function_multi_det.py
> +            wk.reduce_CI_doubles_gpu(
Is the _gpu suffix necessary since everything is namespaced in wk (wicks_gpu)

2024-03-30 00:17 UTC, fdmalone commented on ipie/estimators/kernels/gpu/wicks_gpu.py
> +# # element wise
Remove this commented out code?

2024-03-30 00:18 UTC, fdmalone commented on ipie/estimators/kernels/gpu/wicks_gpu.py
> +# def _reduce_nfold_cofactor_contribution_gpu(ps, qs, mapping, sign, phases, cofactor_matrix, CI):
Remove commented out code.

2024-03-30 00:18 UTC, fdmalone commented on ipie/estimators/kernels/gpu/wicks_gpu.py
> +        # p = cupy.ascontiguousarray(cre[:, iex])
Remove commented out code.

2024-03-30 00:19 UTC, fdmalone commented on ipie/estimators/kernels/gpu/wicks_gpu.py
> +# def reduce_ss_spin_factor_gpu(
Remove commented out code.

2024-03-30 00:20 UTC, fdmalone commented on ipie/estimators/local_energy_wicks.py
> +    # Lvo_a,
Remove commented out code.

2024-03-30 00:20 UTC, fdmalone commented on ipie/estimators/local_energy_wicks.py
> +    nchunks = 1#nwalkers #the number of chunks in the Cholesky dimension, we find in practice setting it to be nwalkers gives a better balance between efficiency and memory-use for large systems
Format the line to avoid formatter complaining.

2024-03-30 00:21 UTC, fdmalone commented on ipie/estimators/local_energy_wicks.py
> +#     free_bytes, total_bytes = xp.cuda.Device().mem_info
Remove commented out code.

2024-03-30 00:21 UTC, fdmalone commented on ipie/propagation/overlap.py
> +        # dets_b = numpy.zeros((nwalkers, ndets_b), dtype=numpy.complex128)
Remove commented out code.

2024-03-30 00:22 UTC, fdmalone commented on ipie/propagation/overlap.py
> +# def compute_determinants_batched(G0a, G0b, trial):
Remove commented out code.

2024-03-30 00:23 UTC, fdmalone commented on ipie/qmc/afqmc.py
> +            if type(self.trial)==ParticleHole:
if not isinstance(self.trail, ParticleHole):
    self.trial.cast_to_cupy(self.verbose and comm.rank == 0)

2024-03-30 00:23 UTC, fdmalone requested changes
Thanks for the contributions!

2024-08-31 17:16 UTC, linusjoonho requested changes

2024-08-31 17:16 UTC, linusjoonho commented on ipie/trial_wavefunction/particle_hole.py
> +        for idet in range(self.num_dets):
Why did you change this to num_dets? We had num_dets_for_props because the code is too slow beyond 100 determinants. I think with lib/wicks we basically removed this bottleneck but if someone is using it without lib/wicks, this code probably should have only up to 100 dets.

2024-08-31 17:16 UTC, linusjoonho commented on ipie/trial_wavefunction/particle_hole.py
> +            for jdet in range(idet + 1, self.num_dets):
This change has the same question.

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/greens_function_multi_det.py
> -@jit(nopython=True, fastmath=True)
Wait, isn't this code used by CPU Wicks? We can't remove jit and also can't use einsum. I think CPU code has been optimized nearly to death so we should not change these unless there's a careful benchmark that suggest changes.

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/greens_function_multi_det.py
> +    G += xp.einsum("wOa, wae, weo-> wOo", Q0_act, CI, Ghalf)
I don't think einsum is faster for CPU.

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/greens_function_multi_det.py
> +        # print(type(walker_batch.CIb))
delete

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/greens_function_multi_det.py
> +    # print(walker_batch.Ghalfa[:, act_orb].copy().shape)
delete

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/kernels/gpu/wicks_gpu.py
> +                #enable_cooperative_groups = True
delete

2024-08-31 17:16 UTC, linusjoonho commented on ipie/estimators/local_energy_wicks.py
> +            exx = xp.einsum("wceE,wcEe->w", T, T)#einsum("wcx,wcx->wc", T.reshape(*T.shape[0:2], -1), tmp.reshape(*tmp.shape[0:2], -1))
Delete the commented part?

2024-08-31 17:16 UTC, linusjoonho commented on ipie/trial_wavefunction/particle_hole.py
> +        self._num_dets_for_props = num_dets_for_props
I think if num_dets_for_props > num_dets from the input, we should handle this exception well. That's why we had min(num_dets, num_dets_for_props above. Maybe change it back?

2024-08-31 17:23 UTC, linusjoonho commented
@yfhuang93 would you fix the merge failures at your earliest convenience? Thank you!

2024-09-03 11:31 UTC, yfhuang93 commented
> @yfhuang93 would you fix the merge failures at your earliest convenience? Thank you!

I forgot to add cupy to requirements.txt and maybe that's why pytests have all the "no module named cupy" errors. I hope this time it works fine.

2024-09-05 02:41 UTC, linusjoonho reviewed
cupy should not be required.

2024-09-05 02:41 UTC, linusjoonho commented on requirements.txt
> +cupy >= 12.0.0
We don't want to require cupy by default, so we cannot have cupy in requirements.txt.
So far I think we have just recommended users to install cupy if GPU features are required.
You would have to "skip" testing your code if cupy is not available for the CI test.

2024-11-05 00:59 UTC, linusjoonho approved these changes
LGTM

2024-11-05 01:01 UTC, merged